"""Testing evidence, operation guide, conclusions, and defense appendices."""
def write_testing(r):
    r.chapter('CHƯƠNG 6. KIỂM THỬ VÀ HƯỚNG DẪN VẬN HÀNH')
    r.h('6.1. Mục tiêu, phương pháp và môi trường')
    r.p('Kiểm thử tập trung vào tính đúng của số tiền, phạm vi thời gian, phân bổ danh mục, toàn vẹn dữ liệu và khả năng giữ dữ liệu khi chuyển từ SQLite cũ sang Room. Các lớp kiểm tra bổ sung cho nhau: unit test không cần thiết bị; instrumentation test dùng SQLite và Room thật trên Android; kiểm tra SQL host đối chiếu schema; thao tác UI xác nhận người dùng có thể nhập và nhận lỗi đúng. Không dùng kết quả của một lớp để khẳng định mọi tình huống ở lớp khác đều đã được kiểm tra.')
    r.table('Môi trường kiểm thử và giới hạn bằng chứng',['Hạng mục','Cấu hình / phạm vi'],[
        ('Máy phát triển','Windows; Android Studio; project D:/AndroidStudioWorkspace/QLCT_LTDD.'),('Thiết bị','AVD QLCT_API_35; Pixel 6; Android 15/API 35; Google APIs x86_64; RAM 4 GB.'),('Ứng dụng','APK debug, package com.example.qlct; database Room version 2.'),('Unit test','JUnit 4.13.2; 4 test AmountValidatorTest và 3 test ExpenseSummaryTest.'),('Instrumentation','ExpenseDatabaseTest: 1 phương thức kiểm thử tích hợp chứa nhiều kiểm tra migration, CRUD và validate.'),('SQL host','docs/tests/test_room_migration.py; so sánh cấu trúc với schema Room xuất bởi KSP.'),('Giới hạn','Chưa kiểm tra đầy đủ trên điện thoại thật, nhiều kích thước màn hình, xoay màn hình, process death và lỗi ổ đĩa.')],[4,12])
    r.h('6.2. Kết quả kiểm thử tự động')
    r.table('Các unit test đã đạt',['Mã','Test / mục tiêu','Kết quả'],[
        ('UT01','negativeAndZeroAmountsAreRejected: -1, -50000, 0, -0 và Long.MIN_VALUE.','Đạt'),('UT02','positiveBoundsAreAccepted: 1, 50000, trim khoảng trắng và MAX_AMOUNT.','Đạt'),('UT03','emptyDecimalsAndMalformedInputAreRejected: rỗng, số thập phân, chữ, dấu sai và tràn Long.','Đạt'),('UT04','amountsAboveLimitAreRejected: 1000000000000 và Long.MAX_VALUE.','Đạt'),('UT05','filtersDoNotChangeChartAndIncomeIsExcludedFromExpense: tổng thu/chi, lọc loại, sáu tháng qua năm mới.','Đạt'),('UT06','emptyMonthsAndLeapDayAreHandled: 29/02 năm nhuận, tháng rỗng và số tiền lớn trong giới hạn.','Đạt'),('UT07','categoryChartGroupsExpensesAndRespectsPeriodButNotTypeFilter: nhóm danh mục, thứ tự giảm dần, bỏ khoản thu.','Đạt')],[1.6,12.5,1.9])
    r.p('Kết quả 7/7 là số phương thức JUnit, không phải số tổ hợp dữ liệu. Một phương thức có thể chạy nhiều giá trị đầu vào. Các báo cáo máy đọc nằm trong app/build/test-results/testDebugUnitTest/*.xml. Test thống kê dùng dữ liệu giả được tạo trong bộ nhớ và kiểm tra giá trị cụ thể; không phụ thuộc giao dịch đang có trên máy ảo.')
    r.table('Các kiểm tra trong instrumentation test',['Nhóm','Điểm đối chiếu','Kết quả'],[
        ('Migration v1 → v2','Tạo database theo schema cũ, mở bằng Room với migration, dữ liệu danh mục/giao dịch và ID được giữ.','Đạt'),('Insert / Read','Thêm giao dịch hợp lệ; đọc được giá trị và tên danh mục qua DAO/Flow.','Đạt'),('Update','Sửa giao dịch cùng ID; kết quả mới thay thế thông tin cũ.','Đạt'),('Delete','Xóa giao dịch đã tạo trong database kiểm thử; không còn dòng đó.','Đạt'),('Persistence','Đóng và mở lại database kiểm thử; dữ liệu đã ghi vẫn còn.','Đạt'),('Database rỗng','Các truy vấn xử lý database rỗng theo hợp đồng.','Đạt'),('Repository validate','Insert và update từ chối tiền âm, 0 và vượt MAX_AMOUNT.','Đạt')],[3,10.8,2.2])
    r.p('Instrumentation đạt 1/1 phương thức. Database kiểm thử tách khỏi dữ liệu sử dụng bình thường; thao tác xóa trong test không có nghĩa là xóa lịch sử của người dùng. Test Room kiểm tra luồng dữ liệu thực trên Android, nhưng không tự động chạm tất cả nút Compose.')
    r.p('Kiểm tra migration bằng Python trên SQLite máy tính đã đạt: chạy SQL chuyển đổi, đối chiếu bảng, cột, chỉ mục, khóa ngoại và dữ liệu bảo toàn với schema Room v2. Kiểm tra SQLite Basic cũ là bằng chứng lịch sử bổ sung, không thay thế instrumentation của bản Room hiện tại. Bản build debug và APK kiểm thử đã tạo thành công; lint gần nhất có 0 lỗi và 15 cảnh báo, chủ yếu liên quan phiên bản dependency, backup rules và tài nguyên không dùng. Không mô tả kết quả lint là không còn cảnh báo.')
    r.h('6.3. Kiểm thử giao diện trực tiếp và ma trận nghiệm thu')
    r.p('Trên máy ảo đã kiểm tra nhập 123 bằng bàn phím số, nhập ghi chú đánh dấu kiểm thử, nhấn Lưu và xác nhận biểu mẫu đóng, giao dịch xuất hiện. Dòng kiểm thử này đã được xóa sau khi xác nhận; không dùng nó làm dữ liệu mẫu của đồ án. Với 0 và -50000, nhấn Lưu hiển thị lỗi “Số tiền phải lớn hơn 0”, giữ biểu mẫu và không ghi giao dịch. Các ảnh chụp chương 5 là bằng chứng giao diện thực. Việc chụp tab hoặc dialog chỉ chứng minh màn hình mở được, không tự động chứng minh toàn bộ chức năng nghiệp vụ đã qua kiểm thử.')
    r.table('Ma trận chức năng và tình trạng xác minh',['Mã','Kịch bản / kết quả mong đợi','Tình trạng'],[
        ('TC01','Mở ứng dụng, tab Tổng quan hiển thị; đọc dữ liệu đã có.','Đã quan sát trên AVD'),('TC02','Thêm khoản chi 123; biểu mẫu đóng và dòng mới xuất hiện.','Đã kiểm tra UI'),('TC03','Nhập 0 hoặc -50000; lỗi inline, không lưu.','Đã kiểm tra UI + unit + repository'),('TC04','Nhập rỗng, chữ, thập phân và vượt giới hạn; bị từ chối.','Unit đạt; cần thử đủ UI'),('TC05','Sửa amount/note và giữ ID; biểu đồ/tổng cập nhật.','Repository đạt; cần nghiệm thu UI đầy đủ'),('TC06','Xóa dòng kiểm thử; dòng không còn.','Đã kiểm tra UI + repository'),('TC07','Bấm Hủy xóa; dữ liệu giữ nguyên.','Cần nghiệm thu UI'),('TC08','Lọc Thu/Chi; tổng kỳ không bị lọc loại làm sai.','Unit đạt; cần thử đủ UI'),('TC09','Đổi tháng qua năm mới; chart có sáu tháng chính xác.','Unit đạt; cần thử đủ UI'),('TC10','Donut nhóm chi theo danh mục, bỏ thu và tôn trọng kỳ.','Unit đạt; đã quan sát màn hình'),('TC11','Migration giữ dữ liệu v1 và mở lại database.','Instrumentation + SQL host đạt'),('TC12','Tạo giao dịch khi không có Internet.','Thiết kế local, không có INTERNET; cần demo offline'),('TC13','Xoay màn hình / process death khi nhập dở.','Chưa kiểm thử đầy đủ'),('TC14','Giả lập lỗi đọc/ghi; Thử lại, giữ biểu mẫu và giải phóng busy.','Có nhánh xử lý; chưa kiểm thử lỗi cưỡng bức'),('TC15','Dữ liệu rất lớn, thiết bị thật và Dark Mode.','Chưa benchmark / chưa nghiệm thu đầy đủ')],[1.5,9.1,5.4])
    r.h('6.4. Cách tái thực hiện các kiểm tra')
    r.steps(['Mở project bằng Android Studio, chờ Gradle Sync hoàn tất. Kiểm tra SDK theo local.properties và phiên bản JDK/Gradle của project.','Chạy unit test và lint bằng lệnh dưới đây; đọc báo cáo XML/HTML trong app/build thay vì chỉ nhìn trạng thái IDE.','Bật QLCT_API_35 trong Device Manager, đợi hệ thống Android khởi động xong; chạy connectedDebugAndroidTest khi thiết bị đã được ADB nhận.','Chạy script migration host sau khi build đã xuất schema KSP. Nếu schema chưa có, thực hiện assembleDebug trước.','Đối chiếu số test, failures/errors và thời điểm chạy. Không đưa kết quả của build cũ vào báo cáo sau khi sửa nghiệp vụ mà chưa chạy lại kiểm tra liên quan.'])
    r.code('.\\gradlew.bat assembleDebug\n.\\gradlew.bat testDebugUnitTest lintDebug\n.\\gradlew.bat connectedDebugAndroidTest\npython docs/tests/test_room_migration.py')
    r.p('Các lệnh được chạy tại thư mục gốc project bằng PowerShell. connectedDebugAndroidTest yêu cầu thiết bị đang chạy; các lệnh còn lại không cần mở app. Thư mục build là sản phẩm sinh tự động và có thể không được commit; vì vậy máy khác cần chạy lại để tạo bằng chứng mới.')
    r.h('6.5. Cài đặt và sử dụng ứng dụng')
    r.steps(['Trong Android Studio, chọn cấu hình app và máy ảo QLCT_API_35, nhấn Run. API 35 đáp ứng minSdk 24 dù target/compile SDK của project là 37.','Lần tạo database mới, app nạp 7 danh mục và 8 giao dịch mẫu theo ngày hiện tại. Cài đè APK giữ database; gỡ app hoặc xóa dữ liệu app sẽ tạo lại dữ liệu khi chạy lần tiếp theo.','Chạm + để thêm. Chọn Thu/Chi, nhập số nguyên dương không có dấu phân cách, chọn danh mục/ngày, thêm ghi chú nếu cần, nhấn Lưu.','Vào Giao dịch để xem danh sách và dùng hành động sửa/xóa ở mỗi dòng. Xóa cần xác nhận; Hủy giữ dữ liệu.','Dùng điều khiển tháng và Tháng này/Toàn bộ để chọn phạm vi tổng hợp; dùng Tất cả/Thu/Chi để lọc danh sách.','Vào Thống kê để đọc tiền chi từng danh mục. Biểu đồ cột luôn là sáu tháng kết thúc tại tháng đang chọn.'])
    r.h('6.6. Lưu ý nhập liệu trên máy ảo')
    r.p('AVD đã cấu hình hw.keyboard=yes, hw.keyboard.lid=no và hiển thị IME với bàn phím vật lý. Người dùng có thể gõ từ bàn phím PC hoặc chạm các phím số Android. Nếu chỉ thấy thanh IME nhỏ, kiểm tra cài đặt bàn phím ảo và cold boot sau thay đổi cấu hình AVD. Đây là cấu hình môi trường, không phải lỗi StateFlow hay Room. Giá trị keyboardType=Number chỉ gợi ý bố cục; validate vẫn bắt buộc với nội dung paste và bàn phím vật lý.')
    r.chapter('CHƯƠNG 7. KẾT LUẬN VÀ HƯỚNG PHÁT TRIỂN')
    r.h('7.1. Kết quả đạt được')
    r.p('Đồ án triển khai được chu trình ghi nhận thu/chi, xem, sửa và xóa giao dịch; chọn thời gian; lọc loại; tính tổng; phân tích chi theo danh mục và sáu tháng. Giao diện Compose chia thành ba tab với phong cách tím thống nhất. MVVM, StateFlow và Repository tạo luồng dữ liệu rõ ràng; Room cung cấp mapping, DAO và migration từ database cũ. Tiền dùng Long và validator chung giữa UI/Repository, chặn số âm, 0, chuỗi sai và vượt giới hạn.')
    r.p('Bằng chứng hiện có xác nhận 7 unit test, 1 instrumentation test tích hợp, kiểm tra SQL migration, build và một số thao tác UI trên AVD. Báo cáo mô tả cả nhánh bình thường, ngoại lệ, trạng thái rỗng và giới hạn. Mức hoàn thiện phù hợp phạm vi ứng dụng quản lý chi tiêu cá nhân cục bộ của đồ án; các chức năng không có trong mã không được tính vào kết quả triển khai.')
    r.h('7.2. Hạn chế hiện tại')
    for x in ['Danh mục cố định; chưa có CRUD danh mục, ngân sách, tìm kiếm nội dung và lọc theo danh mục.','Chưa có tài khoản, đồng bộ đám mây, xuất Excel/PDF hoặc nhập dữ liệu; không có undo sau xóa.','DAO tải toàn bộ giao dịch, summarize chạy trên tập dữ liệu trong bộ nhớ; chưa phân trang, benchmark hoặc chống overflow tổng Long.','Các nhãn phần trăm donut làm tròn xuống; tổng nhãn có thể chưa bằng 100%.','Dữ liệu tài chính chưa mã hóa; cấu hình backup còn điểm cần hoàn thiện; không khẳng định đây là giải pháp bảo mật tài chính ở mức thương mại.','Chưa kiểm thử đầy đủ thiết bị thật, accessibility, dark theme, xoay màn hình, process death và lỗi cưỡng bức.']: r.bullet(x)
    r.h('7.3. Kế hoạch phát triển theo mức ưu tiên')
    r.table('Đề xuất phát triển sau phạm vi hiện tại',['Ưu tiên','Nội dung','Điều kiện nghiệm thu đề xuất'],[
        ('1','Hoàn thiện nghiệm thu UI và accessibility; thêm Compose UI tests.','TC04–TC15 được thực hiện, kết quả và ảnh bằng chứng được lưu.'),('2','Tìm kiếm, lọc danh mục, CRUD danh mục.','Quy định xử lý danh mục đã được giao dịch tham chiếu; có migration mới.'),('3','Ngân sách tháng và cảnh báo vượt mức.','Xác định rõ ngưỡng, kỳ và danh mục; unit test biên tháng.'),('4','Export/import, backup do người dùng điều khiển.','Có preview trước import, validate và chống ghi trùng.'),('5','Tối ưu truy vấn tổng hợp, phân trang và chống tràn tổng.','Đo với dữ liệu lớn, so sánh độ đúng và thời gian đáp ứng.'),('6','Tài khoản/đồng bộ nếu yêu cầu thay đổi.','Thiết kế xác thực, quyền truy cập, xung đột và bảo vệ dữ liệu trước triển khai.')],[1.6,6.3,8.1])
    r.p('Bảng trên là hướng phát triển, không phải danh sách tính năng đã hoàn thành. Mỗi thay đổi database cần tăng version, bổ sung migration và kiểm tra dữ liệu cũ; không dùng destructive migration để tiện thử nghiệm trên dữ liệu thật.')
    r.chapter('TÀI LIỆU THAM KHẢO')
    for num,title,url in [(1,'Android Developers — Jetpack Compose documentation','https://developer.android.com/develop/ui/compose/documentation'),(2,'Android Developers — Guide to app architecture','https://developer.android.com/topic/architecture'),(3,'Android Developers — ViewModel overview','https://developer.android.com/topic/libraries/architecture/viewmodel'),(4,'Android Developers — Save data in a local database using Room','https://developer.android.com/training/data-storage/room'),(5,'Android Developers — Migrate your Room database','https://developer.android.com/training/data-storage/room/migrating-db-versions')]:
        r.p(f'[{num}] {title}. {url}. Truy cập ngày 06/10/2026.')
    r.p('[6] Mã nguồn đồ án QLCT_LTDD: app/src/main, app/src/test, app/src/androidTest, app/schemas và docs/tests. Phiên bản đối chiếu ngày 06/10/2026. Các mô tả chức năng và cấu trúc SQL trong báo cáo được đối chiếu trực tiếp với repository.')
    r.chapter('PHỤ LỤC A. ÁNH XẠ MÃ NGUỒN VÀ TÀI LIỆU')
    r.table('Tệp phục vụ đọc và bảo vệ đồ án',['Tệp / thư mục','Vai trò'],[
        ('app/src/main/java/com/example/qlct/MainActivity.kt','Điểm vào Activity và thiết lập giao diện.'),('app/src/main/java/com/example/qlct/ui/ExpenseScreen.kt','Ba tab, editor, dialog xóa, điều khiển lọc và vẽ biểu đồ.'),('app/src/main/java/com/example/qlct/ui/ExpenseViewModel.kt','UiState, StateFlow, SavedStateHandle, save/delete/retry và summarize.'),('app/src/main/java/com/example/qlct/data/','Entities, DAO, ExpenseDatabase, ExpenseRepository và AmountValidator.'),('app/src/main/assets/seed.sql','7 danh mục và 8 giao dịch mẫu, nạp khi tạo database mới.'),('app/schemas/','Schema Room xuất để tham chiếu và kiểm tra migration.'),('app/src/test/ và app/src/androidTest/','Unit tests và kiểm thử tích hợp Android.'),('docs/tests/','Kiểm tra SQL migration trên máy tính.'),('docs/report_diagrams.py','Nguồn sinh 12 sơ đồ; PNG/SVG trong docs/diagrams/current/.'),('docs/build_final_report.py và report_sections_*.py','Nguồn biên soạn Word; nội dung và hình có thể chỉnh rồi sinh lại.'),('docs/screenshots/','Ảnh thật từ máy ảo phục vụ minh họa báo cáo.')],[7,9])
    r.p('Các đường dẫn là tương đối từ thư mục gốc project. Thư mục cache .gradle/report-libs chứa thư viện Python phục vụ tạo báo cáo, không phải dependency Android. Báo cáo Basic cũ được giữ như tài liệu lịch sử; báo cáo hiện tại là Bao_cao_Do_an_QLCT_Compose_MVVM_Room.docx.')
    r.chapter('PHỤ LỤC B. KỊCH BẢN THUYẾT TRÌNH VÀ DEMO')
    r.p('Kịch bản này là hướng dẫn đề xuất cho buổi bảo vệ, chưa được tính là kết quả kiểm thử đã chạy. Có thể dùng dữ liệu hiện tại; nếu dùng tổng mẫu phải xác nhận database thật đang có đúng 8 dòng seed. Không xóa dữ liệu cá nhân để khớp con số trong báo cáo.')
    r.table('Kịch bản demo có thể thực hiện',['Bước','Thao tác','Điểm trình bày'],[
        ('1','Giới thiệu mục tiêu và thành viên.','Ứng dụng Android cục bộ, thu/chi, Compose–MVVM–Room.'),('2','Mở Tổng quan; giải thích các thẻ tổng.','Chênh lệch = thu − chi; không phải toàn bộ tài sản.'),('3','Nhấn +; chọn Chi, nhập -50000, nhấn Lưu.','Lỗi inline và biểu mẫu giữ nguyên; database không bị ghi.'),('4','Sửa thành 50000; chọn danh mục và ngày; ghi chú DEMO; Lưu.','Tiền dương, loại quyết định thu/chi; dữ liệu lưu Room.'),('5','Vào Giao dịch, tìm dòng DEMO theo vị trí ngày.','Dòng sắp theo date DESC rồi id DESC.'),('6','Sửa dòng DEMO thành 60000 và lưu.','Giữ ID, các tổng tự cập nhật từ Flow.'),('7','Chọn Thu, Chi và Tất cả.','Danh sách thay đổi; tổng kỳ không phụ thuộc lọc loại.'),('8','Đổi tháng và bật Toàn bộ.','Giải thích period và chart sáu tháng độc lập.'),('9','Vào Thống kê.','Danh mục chỉ cộng chi, số tiền chính xác và phần trăm làm tròn.'),('10','Xóa dòng DEMO, xác nhận.','Dữ liệu và thống kê cập nhật; không có undo.'),('11','Mở ERD và sequence trong báo cáo.','Liên hệ FK, validator, ViewModel và DAO.'),('12','Trình bày test và hạn chế.','Phân biệt đã kiểm tra và cần kiểm tra; kế hoạch phát triển.')],[1.3,7.2,7.5])
    r.p('Nếu demo chọn một ngày ngoài tháng đang xem, giao dịch vẫn được lưu nhưng có thể không xuất hiện trong danh sách của tháng hiện tại. Chuyển sang tháng tương ứng hoặc Toàn bộ để kiểm tra. Đây là hệ quả bộ lọc, không nên kết luận thao tác Lưu thất bại chỉ vì chưa thấy dòng.')
    r.chapter('PHỤ LỤC C. CÂU HỎI BẢO VỆ VÀ GIẢI THÍCH KỸ THUẬT')
    questions=[
        ('Vì sao tiền phải dương trong cả thu và chi?','type đã biểu diễn hướng giao dịch. Lưu số dương giúp sum rõ nghĩa, tránh trừ số âm hai lần và phát hiện nhập nhầm. Chênh lệch tính ra vẫn có thể âm hợp lệ.'),
        ('Vì sao dùng Long thay vì Double?','VND trong phạm vi đồ án dùng số nguyên; Long không có sai số dấu phẩy động khi cộng tiền. Double/Float chỉ dùng ở bước tỷ lệ vẽ. Tổng Long vẫn cần bảo vệ overflow khi mở rộng quy mô.'),
        ('Room khác SQLite như thế nào?','SQLite là hệ quản trị dữ liệu nằm trên thiết bị; Room là lớp mapping/DAO trên SQLite, kiểm tra truy vấn và schema, tích hợp Flow và migration. Room không thay SQLite bằng database trên server.'),
        ('MVVM phân công trách nhiệm ra sao?','View nhận thao tác và hiển thị; ViewModel giữ trạng thái/lọc và phối hợp action; Repository kiểm tra nghiệp vụ và truy cập DAO; Room thực hiện lưu trữ. Composable không viết SQL trực tiếp.'),
        ('Tại sao Flow làm giao diện cập nhật?','Room phát lại kết quả khi bảng liên quan thay đổi; ViewModel combine dữ liệu với lựa chọn lọc thành StateFlow; Compose thu nhận state và tái tạo phần giao diện cần cập nhật.'),
        ('Dữ liệu có mất khi cài bản APK mới không?','Cài đè cùng package giữ dữ liệu. Database v1 có migration sang v2. Gỡ app hoặc clear data làm mất dữ liệu ứng dụng. Chưa có backup/export do người dùng điều khiển.'),
        ('Tại sao không dùng destructive migration?','Nó có thể xóa dữ liệu khi thiếu đường chuyển đổi. Đồ án có dữ liệu thu/chi cần giữ nên migration tạo cấu trúc mới và khôi phục dòng/ID; version khác chưa có migration phải xử lý rõ.'),
        ('Tại sao chart không đổi khi lọc Thu?','Bộ lọc loại áp dụng visible; chart lấy EXPENSE từ toàn bộ rows trong sáu tháng. Tổng kỳ và donut cũng được tính trước lọc loại, để không mất thông tin chi khi xem danh sách thu.'),
        ('Tổng phần trăm donut vì sao có thể là 98%?','Mỗi nhãn bị làm tròn xuống thành số nguyên. Góc vẽ dựa trên tỷ lệ thực nên không thiếu dữ liệu. Có thể nâng cấp cách làm tròn hoặc hiển thị phần thập phân.'),
        ('Foreign key và index có ý nghĩa gì?','category_id tham chiếu categories.id để tránh giao dịch mồ côi; NO ACTION không cho xóa danh mục còn được tham chiếu. Index ngày và category_id hỗ trợ truy vấn/khóa ngoại; không đảm bảo mọi truy vấn JOIN đều không cần sort.'),
        ('Có bảo vệ số âm ngay trong SQL không?','Schema Room v2 hiện không có CHECK cho amount/type. UI và Repository kiểm tra; FK/NOT NULL/UNIQUE là ràng buộc database. Gọi DAO trực tiếp có thể bỏ qua validator nên cần duy trì tầng Repository và cân nhắc CHECK ở nâng cấp sau.'),
        ('Đã kiểm thử mọi màn hình chưa?','Chưa. Có 7 unit test và 1 instrumentation tích hợp, kiểm tra host và một số thao tác UI thật. Các case xoay/process death/lỗi cưỡng bức/thiết bị thật được ghi là chưa nghiệm thu, không ghi thành đạt.')]
    for i,(question,answer) in enumerate(questions,1):
        r.h(f'C.{i}. {question}'); r.p(answer)
    r.chapter('PHỤ LỤC D. CHECKLIST TRƯỚC KHI NỘP')
    for x in ['Bổ sung đúng tên trường, khoa, lớp, giảng viên và năm học ở trang bìa; xác nhận bốn họ tên/mã sinh viên.','Đối chiếu mẫu trình bày của trường; chỉnh lề/font nếu có quy định riêng. Không tự ghi tên giảng viên chưa được xác nhận.','Xác nhận phân công nhóm thực tế; thay phương án đề xuất bằng nội dung được các thành viên thống nhất.','Sau khi sửa nội dung, chọn Ctrl+A rồi F9 trong Word để cập nhật mục lục, danh mục hình/bảng và số trang.','Nghiệm thu các case đang đánh dấu cần kiểm tra; chỉ đổi thành Đạt khi có thao tác/kết quả thực.','Chuẩn bị project mở được, APK debug và máy ảo; tập demo thêm/sửa/xóa bằng dữ liệu đánh dấu riêng.','Không nộp local.properties, khóa ký, database riêng hoặc cache như một phần mã nguồn; tham khảo quy định nộp bài của môn.','Đọc lại giới hạn và tài liệu tham khảo; kiểm tra hình/sơ đồ rõ nét trong cả Word và PDF.']: r.bullet(x)
