"""Introduction, technologies, requirements, and detailed use cases."""

def write_analysis(r):
    r.chapter('CHƯƠNG 1. GIỚI THIỆU ĐỀ TÀI')
    r.h('1.1. Lý do chọn đề tài')
    r.p('Trong sinh hoạt và học tập, các khoản chi nhỏ thường phát sinh nhiều lần trong ngày. Nếu chỉ ghi nhớ hoặc ghi chép rời rạc, người dùng khó biết tổng chi của tháng, khó đối chiếu với thu nhập và khó nhận ra nhóm chi nào chiếm tỷ trọng lớn. Một ứng dụng di động có thể hỗ trợ ghi nhận ngay tại thời điểm phát sinh, tổng hợp lại theo khoảng thời gian và trình bày kết quả bằng các hình thức dễ quan sát.')
    r.p('Đề tài “Ứng dụng quản lý chi tiêu cá nhân” được lựa chọn vì có nghiệp vụ gần gũi, đồng thời tạo điều kiện vận dụng các nội dung quan trọng của môn Lập trình di động: xây dựng giao diện, xử lý sự kiện, quản lý trạng thái, lưu trữ dữ liệu và kiểm thử. Phạm vi được giới hạn vào quản lý giao dịch cục bộ để bảo đảm sản phẩm có thể chạy và trình diễn mà không phụ thuộc tài khoản, mạng hoặc dịch vụ bên ngoài.')
    r.p('Tên gọi QLCT là viết tắt của Quản lý chi tiêu. Ứng dụng là công cụ ghi chép và thống kê dữ liệu do người dùng nhập; không kết nối tài khoản ngân hàng, không tự động lấy giao dịch và không đưa ra quyết định tài chính thay người dùng.')
    r.h('1.2. Mục tiêu của đồ án')
    for t in ['Xây dựng ứng dụng Android có thể thêm, xem, sửa và xóa các giao dịch thu/chi, lưu được dữ liệu sau khi đóng và mở lại.', 'Triển khai giao diện hoàn toàn bằng Jetpack Compose, tổ chức mã theo MVVM và dùng Room làm lớp lưu trữ giao dịch.', 'Tính tổng thu, tổng chi, chênh lệch theo tháng được chọn hoặc toàn bộ thời gian; cung cấp bộ lọc loại giao dịch.', 'Vẽ biểu đồ chi tiêu theo tháng và phân bổ khoản chi theo danh mục từ dữ liệu thực tế, xử lý rõ trường hợp không có dữ liệu.', 'Kiểm tra dữ liệu đầu vào, đặc biệt là số tiền dương, đồng thời bảo toàn dữ liệu khi chuyển từ SQLiteOpenHelper phiên bản cũ sang Room.', 'Hoàn thiện tài liệu phân tích, thiết kế và kiểm thử để giải thích được cách hệ thống hoạt động, không chỉ trình bày ảnh giao diện.']: r.bullet(t)
    r.h('1.3. Đối tượng sử dụng và phạm vi')
    r.p('Đối tượng sử dụng là người dùng cá nhân cần ghi lại các khoản thu và chi bằng VND trên một thiết bị Android. Mỗi bản cài đặt có một database riêng; hệ thống không có tài khoản và không tách nhiều hồ sơ người dùng. Trong mô hình use case chỉ có một actor “Người dùng”.')
    r.table('Phạm vi triển khai và phần chưa triển khai',['Nhóm','Nội dung'],[
        ('Đã triển khai','CRUD giao dịch; 7 danh mục cố định; chọn ngày; ghi chú; chọn tháng; lọc Thu/Chi; tổng quan; biểu đồ vòng; biểu đồ cột 6 tháng; migration v1→v2.'),
        ('Chưa triển khai','Đăng nhập; đồng bộ cloud; ngân sách; nhắc nhở; xuất/nhập dữ liệu; CRUD danh mục; tìm kiếm từ khóa; lọc riêng theo danh mục.'),
        ('Giới hạn môi trường','Android API 24 trở lên; compileSdk/targetSdk 37; kiểm tra chạy thực tế hiện có trên Pixel 6 máy ảo Android 15/API 35.'),
        ('Giới hạn dữ liệu','VND dạng số nguyên; không hỗ trợ đa tiền tệ; các giao dịch được nạp toàn bộ và tổng hợp trong bộ nhớ.')],[3.3,12.7])
    r.h('1.4. Yêu cầu kỹ thuật của đề tài')
    r.table('Đối chiếu yêu cầu chính thức với thành phần hiện thực',['Yêu cầu','Thành phần đáp ứng','Bằng chứng'],[
        ('100% Jetpack Compose','setContent, ExpenseScreen, TransactionEditor, DashboardComponents','Không có res/layout trong giao diện hiện tại; DatePicker và các dialog là Compose.'),
        ('Kiến trúc MVVM','ExpenseViewModel, ExpenseRepository, ExpenseDao, ExpenseUiState','Giao diện gửi sự kiện vào ViewModel; trạng thái quan sát bằng StateFlow.'),
        ('Room lưu giao dịch','ExpenseDatabase, Category, TransactionEntity, ExpenseDao','@Database version=2; @Entity; @Dao; KSP xuất schema 2.json.'),
        ('Biểu đồ chi tiêu tháng','summarize(), MonthlyExpense, SpendingChart','6 cột tương ứng 6 tháng kết thúc tại tháng được chọn; chỉ cộng khoản EXPENSE.')],[3.3,5.2,7.5])
    r.p('Việc còn các file XML như AndroidManifest.xml, theme hoặc drawable không vi phạm yêu cầu không dùng XML layout. Các file này phục vụ cấu hình ứng dụng và tài nguyên, còn các màn hình nghiệp vụ được dựng bằng Compose.')

    r.h('1.4.1. Đề bài chính thức và phạm vi bắt buộc',3)
    r.p('Theo bảng yêu cầu được cung cấp, nhóm 1 có chủ đề “Jetpack Compose”, đề tài đồ án cuối kỳ “Ứng dụng Quản lý chi tiêu cá nhân”. Yêu cầu kỹ thuật bắt buộc được ghi nguyên văn: “Giao diện 100% Jetpack Compose (không XML); kiến trúc MVVM; Room lưu giao dịch; biểu đồ chi tiêu theo tháng.” Đây là căn cứ chính của phần triển khai và đánh giá kết quả báo cáo.')
    r.p('Bốn yêu cầu phải được đáp ứng đồng thời. Thêm/sửa/xóa, lọc và tổng thu/chi là nghiệp vụ phục vụ đề tài. Validate tiền là yêu cầu bổ sung đã thống nhất. Biểu đồ vòng danh mục hỗ trợ phân tích; biểu đồ cột tháng đáp ứng trực tiếp yêu cầu bắt buộc. Đăng nhập, cloud, ngân sách và export từ ứng dụng chưa có trong ảnh đề bài và chưa được tính là tính năng đã triển khai.')
    r.h('1.4.2. Diễn giải giao diện 100% Jetpack Compose',3)
    r.p('Yêu cầu quy định công nghệ dựng toàn bộ màn hình nghiệp vụ. Tổng quan, lịch sử, thống kê, biểu mẫu thêm/sửa, xác nhận xóa, bộ chọn ngày, ô tiền, chip lọc và điều hướng được dựng bằng hàm Composable trong Kotlin, không bố trí bằng XML layout.')
    r.p('MainActivity gọi setContent để khởi tạo giao diện. ExpenseScreen điều phối ba tab; TransactionEditor tạo biểu mẫu bằng Compose Material 3. Các thành phần nhận giá trị từ state và phát sự kiện khi người dùng thao tác. Khi state đổi, Compose cập nhật phần giao diện phụ thuộc state; không dùng findViewById để sửa từng nhãn.')
    r.p('Ví dụ nhập 0 và nhấn Lưu: validator trả lỗi, ô tiền chuyển trạng thái lỗi và supportingText hiện thông báo. Sửa thành 50000 làm kiểm tra được tính lại. Loại, danh mục, ngày và ghi chú cũng được giữ bằng state.')
    r.p('XML manifest/theme/drawable là cấu hình và tài nguyên Android, không phải layout màn hình. Cách chứng minh là kiểm tra setContent, @Composable và không có XML layout được dùng để dựng màn hình. Demo mở ba tab, editor, danh mục và DatePicker để trình bày cả màn hình chính lẫn dialog; ảnh chương 5 là giao diện chạy thật.')
    r.h('1.4.3. Diễn giải kiến trúc MVVM',3)
    r.p('MVVM tách View, ViewModel và Model để giao diện không tự viết SQL và lớp dữ liệu không điều khiển nút/dialog. View là các Composable, nhận thao tác và hiển thị ExpenseUiState, busy và lỗi. ExpenseViewModel giữ tháng/bộ lọc bằng SavedStateHandle, combine Flow, tính summarize và điều phối save/delete trong viewModelScope.')
    r.p('Model gồm entity, ExpenseRepository, ExpenseDao và ExpenseDatabase. Repository kiểm tra nghiệp vụ; DAO định nghĩa truy vấn; Room lưu SQLite. Các lớp này không dựng giao diện và không tự đóng biểu mẫu.')
    r.p('Luồng thêm: View nhận dữ liệu hợp lệ → ViewModel.save bật busy → Repository kiểm tra tiền/loại/ngày/danh mục → DAO insert Room. Ghi thành công làm completedActions tăng để View đóng biểu mẫu. Room phát Flow mới, ViewModel tổng hợp và Compose hiện tổng/biểu đồ mới. Hoàn tất ghi và phát Flow là các sự kiện bất đồng bộ.')
    r.p('Luồng đổi bộ lọc: View gửi lựa chọn → ViewModel cập nhật SavedStateHandle → combine tạo UiState → Compose đổi danh sách. Không ghi database. Chứng minh MVVM bằng trách nhiệm và chiều phụ thuộc của lớp qua một thao tác cụ thể, liên hệ sơ đồ kiến trúc/class/sequence; không chỉ nhìn tên ViewModel.')
    r.h('1.4.4. Diễn giải Room lưu giao dịch',3)
    r.p('Dữ liệu phải được lưu bền vững trên thiết bị, không chỉ ở danh sách tạm. Room là lớp truy cập SQLite qua entity, DAO và quản lý phiên bản database. Các chức năng hiện tại không cần server.')
    r.p('ExpenseDatabase khai báo qlct.db version 2; Category ánh xạ categories, TransactionEntity ánh xạ transactions gồm ID, loại, tiền, category_id, ngày và note. category_id tham chiếu categories.id. ID giao dịch tự tăng, ID danh mục được xác định bởi dữ liệu khởi tạo.')
    r.p('ExpenseDao dùng @Insert, @Update và delete; truy vấn Flow JOIN danh mục lấy tên, sắp date DESC rồi id DESC. Insert trả ID mới; update/delete trả số dòng để Repository kiểm tra tác động đúng bản ghi. Room bảo vệ PK/FK/NOT NULL/index; tiền dương được kiểm tra tại UI/Repository vì schema v2 chưa có CHECK cho amount/type.')
    r.p('Có thể demo bằng cách thêm dòng đánh dấu, đóng/mở lại và đối chiếu dữ liệu. Instrumentation đã kiểm tra CRUD, mở lại và migration v1→v2. Cài đè APK giữ dữ liệu; gỡ app/clear storage xóa dữ liệu riêng. seed.sql khởi tạo một lần; nhấn Lưu về sau đi qua Repository/DAO chứ không sửa seed.')
    r.h('1.4.5. Diễn giải biểu đồ chi tiêu theo tháng',3)
    r.p('Biểu đồ lấy giao dịch đã lưu, chỉ chọn EXPENSE và cộng amount theo tháng của date. Mỗi cột có tháng rõ ràng; tháng rỗng nhận 0; INCOME không cộng vào cột chi.')
    r.p('summarize tạo sáu tháng M−5 đến M, M là tháng được chọn. Ví dụ M=10/2026, chart là 05/2026 đến 10/2026. MonthlyExpense giữ tháng/tổng chi và SpendingChart vẽ cột. Chiều cao chuẩn hóa theo tổng lớn nhất với mẫu số ít nhất 1 tránh chia 0. Tiền giữ Long; kiểu thực phục vụ tỷ lệ vẽ.')
    r.p('Với database mới chưa chỉnh sửa, sáu khoản chi mẫu 45.000, 70.000, 150.000, 250.000, 800.000 và 30.000 tạo cột tháng khởi tạo 1.345.000 VND. Hai khoản thu 3.000.000 và 1.200.000 không vào chart. Các tháng trước nhận 0 nếu chưa có giao dịch; không tự sinh số liệu.')
    r.p('Thêm/sửa/xóa chi làm Flow phát dữ liệu và chart tính lại. Lọc Thu/Chi chỉ tác động visible; chart luôn dùng chi từ toàn bộ rows trong sáu tháng. Toàn bộ thay đổi kỳ của danh sách/tổng/donut, nhưng chart vẫn là sáu tháng kết thúc tại M.')
    r.p('Nghiệm thu bằng các khoản chi ở hai tháng và một khoản thu: cộng tay từng tháng, đối chiếu cột; kiểm tra tháng rỗng và 12→1. Unit test đã kiểm tra cửa sổ sáu tháng, bỏ thu và độc lập lọc loại. Donut là phần bổ trợ, không thay thế chart tháng bắt buộc.')
    r.h('1.5. Nhóm thực hiện và phương án phân công')
    r.table('Phân công đề xuất để hoàn thiện và bảo vệ đồ án',['Thành viên / MSSV','Phần đề xuất phụ trách','Sản phẩm chuẩn bị'],[
        ('Nguyễn Như Vũ\n25610008','Mô hình dữ liệu, Room, DAO, migration','Giải thích ERD; schema; truy vấn; bảo toàn dữ liệu và test database.'),
        ('Nguyễn Văn Vũ\n25810053','Giao diện Compose và biểu mẫu giao dịch','Trình diễn thêm/sửa/xóa; xử lý bàn phím, danh mục, DatePicker và validate.'),
        ('Nguyễn Thiên Vọng\n25810050','ViewModel, lọc và thống kê','Giải thích StateFlow, tổng quan, biểu đồ vòng/cột và các công thức tổng hợp.'),
        ('Nguyễn Văn Phước\n25810035','Tích hợp, kiểm thử, báo cáo và trình diễn','Tổng hợp bằng chứng kiểm thử; kịch bản demo; định dạng Word và chuẩn bị slide.')],[4.1,5.4,6.5])
    r.p('Bảng trên là đề xuất phân công, cần nhóm xác nhận theo phần việc thực tế. Báo cáo không gán tỷ lệ đóng góp, thời gian làm việc hoặc thành tích cá nhân khi chưa có dữ liệu xác nhận.')
    r.h('1.6. Phương pháp thực hiện và cấu trúc báo cáo')
    r.p('Phương pháp thực hiện gồm xác định phạm vi, phân tích các thao tác của người dùng, thiết kế dữ liệu và trạng thái, xây dựng giao diện, kiểm tra nghiệp vụ, chạy máy ảo và đối chiếu tài liệu với mã. Các sơ đồ trong báo cáo phản ánh cấu trúc hiện tại, không lấy các chức năng ngân sách hoặc quản lý danh mục ở đề cương cũ làm kết quả đã hoàn thành.')
    r.p('Báo cáo gồm bảy chương: giới thiệu; công nghệ; phân tích yêu cầu và use case; thiết kế kiến trúc và dữ liệu; triển khai chức năng và giao diện; kiểm thử và hướng dẫn vận hành; kết luận. Phụ lục cung cấp cấu trúc mã, truy vấn, kịch bản demo và câu hỏi chuẩn bị bảo vệ.')

    r.chapter('CHƯƠNG 2. CƠ SỞ CÔNG NGHỆ')
    r.h('2.1. Android và Kotlin')
    r.p('Android là nền tảng chạy ứng dụng. Kotlin được sử dụng cho Activity, lớp dữ liệu, repository, ViewModel và toàn bộ hàm giao diện Compose. data class giúp biểu diễn các đối tượng như TransactionEntity, TransactionRow và ExpenseUiState với cấu trúc rõ ràng. Giá trị null được dùng trong các kết quả validate để biểu thị không có thông báo lỗi.')
    r.p('Project sử dụng Android Gradle Plugin 9.4.1 với hỗ trợ Kotlin tích hợp. Compose compiler plugin dùng phiên bản 2.2.10; KSP 2.3.6 sinh mã cho Room. Java sourceCompatibility và targetCompatibility là 11, trong khi JVM chạy Gradle được cấu hình bằng toolchain của project. Không đồng nhất hai khái niệm mức bytecode đích và JDK chạy hệ thống build.')
    r.h('2.2. Jetpack Compose và Material 3')
    r.p('Compose là công cụ xây dựng giao diện Android theo cách khai báo [1]. Trong QLCT, một hàm @Composable nhận dữ liệu và mô tả thành phần cần hiển thị. Khi state thay đổi, Compose tái kết hợp các phần liên quan để giao diện phản ánh dữ liệu mới. Không tìm View bằng findViewById và không tạo XML layout cho các trang nghiệp vụ.')
    r.p('Material 3 cung cấp Scaffold, Surface, AlertDialog, OutlinedTextField, FilterChip, DatePickerDialog và các nút. Các thành phần này được kết hợp với Row, Column, Box và LazyColumn để tạo giao diện tông tím. RoundedCornerShape tạo thẻ bo góc; Brush tạo gradient ở phần đầu; Canvas dùng để vẽ biểu đồ và icon bằng mã.')
    r.p('Giao diện có ba tab do biến tab lưu bằng rememberSaveable điều khiển. Đây là điều hướng bằng trạng thái trong một Activity; project hiện tại không dùng NavController. Các biểu mẫu thêm/sửa, menu danh mục, chọn ngày và xác nhận xóa là lớp giao diện tạm thời phủ lên trang đang xem.')
    r.h('2.3. Kiến trúc MVVM')
    r.p('MVVM chia trách nhiệm giữa View, ViewModel và Model. View tiếp nhận thao tác và hiển thị; ViewModel giữ trạng thái, xử lý các lệnh và kết nối dữ liệu với màn hình; Model bao gồm entity, repository, DAO và database. Cách tách trách nhiệm này phù hợp với định hướng phân lớp của Android [2] và đặc điểm ViewModel [3].')
    r.p('ExpenseScreen không tự chạy SQL. Khi nhấn Lưu, giao diện tạo TransactionEntity và gọi model.save(). ExpenseViewModel thực hiện tác vụ trong viewModelScope, cập nhật trạng thái busy và actionError. ExpenseRepository kiểm tra quy tắc nghiệp vụ trước khi gọi DAO. Room chịu trách nhiệm thực thi truy cập SQLite và phát lại dữ liệu qua Flow.')
    r.h('2.4. Flow, StateFlow, lifecycle và lưu trạng thái')
    r.p('DAO trả Flow cho danh mục và danh sách giao dịch. ViewModel dùng combine để kết hợp hai luồng dữ liệu với ba tham số month, monthOnly và type. Hàm summarize tạo kết quả tổng hợp, sau đó stateIn chuyển kết quả thành StateFlow cung cấp ExpenseUiState cho giao diện. SharingStarted.WhileSubscribed(5_000) duy trì chia sẻ trong một khoảng ngắn sau khi không còn subscriber.')
    r.p('ExpenseScreen dùng collectAsStateWithLifecycle để quan sát state trong vòng đời màn hình. SavedStateHandle lưu tháng và các bộ lọc; rememberSaveable lưu các trạng thái của biểu mẫu như loại, số tiền, ngày, ghi chú và ID đang chỉnh sửa. Cơ chế này hỗ trợ tái tạo giao diện, nhưng không nên diễn đạt thành bảo đảm mọi tình huống tắt cưỡng bức hoặc mọi giao dịch đang ghi đều được khôi phục; các tình huống đó cần kiểm thử riêng.')
    r.p('busy ngăn lặp thao tác ghi; actionError mang thông báo lỗi; completedActions tăng sau khi thao tác thành công. Giao diện dùng LaunchedEffect quan sát completedActions để đóng hộp thoại. Dữ liệu thực tế không được cập nhật bằng cách sửa danh sách hiển thị thủ công; danh sách mới xuất phát từ Flow của Room.')
    r.h('2.5. Room và SQLite')
    r.p('Room là thư viện cung cấp lớp truy cập dữ liệu trên SQLite [4]. Entity định nghĩa bảng, DAO định nghĩa thao tác truy cập, RoomDatabase cung cấp database và DAO. SQLite vẫn là hệ quản trị lưu trữ thực tế trên thiết bị. Người dùng không cần cài SQLite server hoặc dịch vụ database riêng.')
    r.p('Project dùng Room 2.8.4, xuất schema version 2 để lưu cấu trúc có thể kiểm tra. Database tên qlct.db nằm trong vùng dữ liệu riêng của ứng dụng. Room được mở bằng singleton để hạn chế tạo nhiều đối tượng quản lý cùng file. Các thao tác ghi DAO là suspend và không dùng allowMainThreadQueries().')
    r.p('Migration là quá trình nâng cấp cấu trúc database mà vẫn giữ dữ liệu [5]. MIGRATION_1_2 chuyển bảng tạo bởi SQLiteOpenHelper cũ sang schema mà Room kỳ vọng, đặc biệt là nullability của khóa chính và định nghĩa chỉ mục. Không dùng fallbackToDestructiveMigration(), vì vậy một phiên bản chưa có đường migration phù hợp sẽ không tự xóa database để mở lại.')
    r.h('2.6. Long, ngày tháng và tính chính xác')
    r.p('Số tiền VND được lưu bằng Long để giữ chính xác giá trị nguyên và tránh sai số kiểu dấu phẩy động trong phép cộng. Mức nhập hợp lệ là 1 đến 999.999.999.999. Thu và chi đều lưu số dương; field type quyết định cách tính và dấu khi hiển thị. Chênh lệch tổng thu trừ tổng chi được phép âm vì đó là kết quả tổng hợp, không phải số tiền của một giao dịch.')
    r.p('Ngày lưu theo chuỗi ISO yyyy-MM-dd và được kiểm tra bằng LocalDate.parse(). Tháng được biểu diễn bằng YearMonth. DatePicker truyền mốc thời gian UTC rồi chuyển thành LocalDate theo UTC để không làm lệch ngày do đổi múi giờ. Dữ liệu mẫu được SQLite tạo ngày theo localtime của thiết bị khi database được tạo lần đầu.')
    r.h('2.7. Cấu hình thư viện của bản báo cáo')
    r.table('Công nghệ và phiên bản từ cấu hình project',['Thành phần','Phiên bản / giá trị','Vai trò'],[
        ('Android Gradle Plugin','9.4.1','Build ứng dụng Android; Kotlin tích hợp'),('Kotlin Compose compiler','2.2.10','Biên dịch các hàm Compose'),('Compose BOM','2025.08.00','Đồng bộ các thư viện Compose'),('Activity Compose','1.11.0','ComponentActivity.setContent'),('Lifecycle','2.9.4','ViewModel, StateFlow và quan sát lifecycle'),('Room','2.8.4','Entity, DAO, database và test'),('KSP','2.3.6','Sinh mã Room'),('JUnit','4.13.2','Unit test'),('minSdk / targetSdk / compileSdk','24 / 37 / 37','Mức Android tối thiểu và API biên dịch'),('Máy ảo kiểm tra','Pixel 6, API 35, x86_64, RAM 4 GB','Trình diễn giao diện và chạy instrumentation')],[4.2,4.0,7.8])

    r.chapter('CHƯƠNG 3. PHÂN TÍCH YÊU CẦU VÀ USE CASE')
    r.h('3.1. Bài toán nghiệp vụ và quy tắc chung')
    r.p('Người dùng ghi nhận một giao dịch bằng sáu thông tin: loại thu/chi, số tiền, danh mục, ngày và ghi chú, cùng ID do hệ thống quản lý. Một giao dịch thuộc một danh mục trong danh sách có sẵn. Thao tác chỉnh sửa thay đổi chính bản ghi đã chọn; thao tác xóa loại bỏ bản ghi sau khi được xác nhận. Hệ thống phải tính lại thông tin tổng hợp khi dữ liệu thay đổi.')
    r.table('Các quy tắc nghiệp vụ đang áp dụng',['Mã','Quy tắc','Thành phần chịu trách nhiệm'],[
        ('BR01','type chỉ INCOME hoặc EXPENSE','Biểu mẫu và ExpenseRepository'),('BR02','amount là số nguyên từ 1 đến 999.999.999.999','AmountValidator dùng chung; repository kiểm tra lại'),('BR03','categoryId phải là danh mục tồn tại','Chọn trong biểu mẫu; FK của database bảo vệ tham chiếu'),('BR04','Ngày lưu theo yyyy-MM-dd; không cấm ngày tương lai','DatePicker và LocalDate.parse trong repository'),('BR05','Ghi chú không bắt buộc; trim trước khi lưu','ExpenseRepository; schema note NOT NULL DEFAULT \'\''),('BR06','Thu/chi đều lưu tiền dương; tổng chênh lệch có thể âm','TransactionEntity và summarize'),('BR07','Tổng quan và donut không đổi theo bộ lọc Thu/Chi','summarize tính period trước visible'),('BR08','Biểu đồ cột gồm 6 tháng, độc lập monthOnly và type','summarize tạo chart từ toàn bộ rows'),('BR09','Chỉ đóng dialog sau thao tác ghi thành công','completedActions và LaunchedEffect'),('BR10','Dữ liệu mẫu chỉ xuất hiện khi tạo database mới','Room callback.onCreate')],[1.5,9.0,5.5])
    r.h('3.2. Yêu cầu chức năng')
    r.table('Danh sách yêu cầu chức năng',['Mã','Yêu cầu','Tiêu chí quan sát'],[
        ('FR01','Xem tổng quan thu/chi','Tổng thu, chi và chênh lệch phản ánh thời gian đang chọn.'),('FR02','Thêm khoản thu hoặc chi','Nhập hợp lệ, lưu vào Room và xuất hiện trong danh sách.'),('FR03','Xem danh sách và chi tiết ngắn','Sắp xếp ngày giảm dần, ID giảm dần; hiển thị danh mục, tiền, ngày, ghi chú.'),('FR04','Sửa một giao dịch','Biểu mẫu nạp giá trị cũ; update đúng ID; tổng hợp phản ánh dữ liệu mới.'),('FR05','Xóa có xác nhận','Hủy không xóa; xác nhận mới gọi DAO.delete().'),('FR06','Chọn tháng hoặc toàn bộ thời gian','Nút trước/sau đổi tháng; nút Theo tháng/Toàn bộ đổi phạm vi.'),('FR07','Lọc Tất cả/Thu/Chi','Tab Giao dịch dùng FilterChip; danh sách phù hợp loại đã chọn.'),('FR08','Xem phân bổ chi theo danh mục','Chỉ dùng khoản chi trong period; donut và chú giải tương ứng.'),('FR09','Xem chi tiêu theo tháng','6 tháng liên tiếp; tháng không có khoản chi nhận 0.'),('FR10','Xử lý lỗi và dữ liệu rỗng','Báo lỗi nhập; giữ form khi ghi thất bại; có Thử lại khi tải lỗi.')],[1.5,5.4,9.1])
    r.h('3.3. Yêu cầu phi chức năng')
    r.p('Tính toàn vẹn: không lưu số tiền âm/0 qua repository; danh mục được tham chiếu bằng khóa ngoại; cập nhật/xóa kiểm tra số dòng tác động. Khả năng sử dụng: giao diện tiếng Việt, phân biệt thu/chi bằng nhãn và màu, có thông báo ngay dưới ô tiền và xác nhận trước khi xóa. Khả năng bảo trì: chia file theo UI và data, tách summarize và AmountValidator để test mà không cần chạy UI.')
    r.p('Khả năng hoạt động cục bộ: các chức năng hiện có không cần mạng; manifest không khai báo quyền INTERNET. Hiệu năng: LazyColumn chỉ dựng các dòng cần hiển thị nhưng ViewModel vẫn nhận toàn bộ dữ liệu; vì vậy không khẳng định hệ thống đã tối ưu cho hàng trăm nghìn giao dịch. Bảo mật: dữ liệu nằm trong vùng riêng của ứng dụng, nhưng chưa mã hóa database và chưa khóa ứng dụng bằng sinh trắc học.')
    r.h('3.4. Actor và sơ đồ use case')
    r.p('Actor “Người dùng” khởi tạo các thao tác trực tiếp trên giao diện. Use case thêm và sửa dùng chung bước kiểm tra dữ liệu; use case xóa bao gồm bước xác nhận. Các bước kỹ thuật này được biểu diễn bằng quan hệ include để làm rõ hành vi luôn cần thực hiện, không phải chức năng ngân sách hoặc tài khoản.')
    r.image('docs/diagrams/current/01_use_case.png','Use case tổng quát của bản Compose/MVVM/Room')
    cases=[
        ('UC01','Xem tổng quan','Mở ứng dụng hoặc chọn tab Tổng quan','Database tải thành công; có thể có hoặc không có giao dịch',
         ['Hệ thống nhận danh mục và giao dịch từ Flow của Room.', 'ViewModel đọc tháng, chế độ thời gian và loại lọc đang lưu.', 'summarize tính tổng thu, tổng chi, chênh lệch và dữ liệu biểu đồ.', 'Màn hình hiển thị thẻ tổng quan, donut, cột 6 tháng và tối đa 4 giao dịch gần đây.', 'Người dùng nhấn Xem tất cả để chuyển sang tab Giao dịch nếu cần xem toàn bộ danh sách.'],
         ['Đang tải: hiển thị CircularProgressIndicator.', 'Tải lỗi: hiển thị thông báo và nút Thử lại; không giả định database rỗng.', 'Không có dữ liệu trong period: các tổng bằng 0, danh sách có lời nhắc thêm giao dịch và donut hiển thị vòng nền.'],
         'Không ghi database. Số liệu phản ánh period; danh sách gần đây còn chịu bộ lọc type đã chọn trước đó.',
         'Đối chiếu tổng trên giao diện với dữ liệu mẫu; thử tháng rỗng và phạm vi toàn bộ.'),
        ('UC02','Thêm giao dịch','Nhấn nút + trên thanh điều hướng dưới','Đã tải danh mục; không có thao tác ghi đang chạy',
         ['Biểu mẫu mặc định loại EXPENSE, số tiền trống, danh mục đầu tiên, ngày hiện tại, ghi chú trống.', 'Người dùng chọn Chi tiền hoặc Thu tiền.', 'Người dùng nhập số tiền nguyên VND; chọn danh mục từ DropdownMenu.', 'Người dùng có thể chọn lại ngày bằng DatePickerDialog và nhập ghi chú.', 'Nhấn Lưu: hệ thống đánh dấu đã kiểm tra tiền, gọi AmountValidator và xác nhận danh mục trong danh sách.', 'Nếu hợp lệ, tạo TransactionEntity với id=0 và chuyển tới ViewModel.save().', 'ViewModel bật busy; repository kiểm tra tiền, loại, ngày, danh mục và trim ghi chú.', 'DAO.insert() sinh ID; thao tác hoàn tất làm completedActions tăng.', 'Dialog đóng; Flow phát danh sách mới; các tổng và biểu đồ tự tính lại.'],
         ['Số tiền rỗng: “Vui lòng nhập số tiền”.', 'Số âm hoặc 0: “Số tiền phải lớn hơn 0”.', 'Chuỗi không chuyển được sang Long: “Nhập số tiền nguyên hợp lệ (VND)”.', 'Tiền vượt 999.999.999.999: báo mức tối đa.', 'Thiếu danh mục: yêu cầu chọn; lỗi ghi: actionError và giữ dữ liệu nhập để thử lại.', 'Nhấn Hủy hoặc đóng dialog khi không busy: không ghi bản ghi mới.'],
         'Một giao dịch mới được lưu bền vững nếu thao tác thành công; không có bản ghi mới khi validate thất bại hoặc người dùng hủy.',
         'Kiểm tra khoản chi/thu hợp lệ; nhập 0, âm, rỗng, chữ, số thập phân và vượt giới hạn; kiểm tra tránh nhấn Lưu lặp.'),
        ('UC03','Xem lịch sử giao dịch','Chọn tab Giao dịch hoặc Xem tất cả','Đã tải dữ liệu',
         ['Màn hình giữ thẻ tổng quan và vùng chọn thời gian.', 'Hiển thị các chip Tất cả, Thu, Chi và số giao dịch phù hợp.', 'Mỗi dòng có icon danh mục, tên, ngày dd/MM, ghi chú rút gọn, số tiền có dấu và nút thùng rác.', 'Danh sách theo t.date DESC rồi t.id DESC từ truy vấn DAO.', 'Người dùng cuộn LazyColumn để xem các giao dịch còn lại.', 'Chạm dòng mở sửa; chạm thùng rác mở xác nhận xóa.'],
         ['Danh sách rỗng sau lọc: hiển thị thẻ Chưa có giao dịch và gợi ý nút +.', 'Ghi chú dài bị rút gọn trên dòng nhưng được nạp đầy đủ khi mở biểu mẫu sửa.', 'Trong lúc busy, các hành động sửa/xóa bị vô hiệu hóa.'],
         'Không ghi database nếu người dùng chỉ xem hoặc cuộn.',
         'Kiểm tra thứ tự cùng ngày, số lượng, dấu Thu/Chi và nội dung ghi chú khi mở sửa.'),
        ('UC04','Sửa giao dịch','Chạm một dòng giao dịch','Giao dịch tồn tại trong danh sách visible; không busy',
         ['ExpenseScreen ghi editingId và mở TransactionEditor với existing tương ứng.', 'Biểu mẫu nạp loại, tiền, categoryId, date và note của bản ghi cũ.', 'Người dùng thay đổi một hoặc nhiều trường và nhấn Lưu.', 'Áp dụng cùng quy tắc tiền và danh mục như thêm mới.', 'TransactionEntity giữ existing.id; repository nhận biết id khác 0.', 'DAO.update() trả số dòng; repository yêu cầu đúng 1 dòng.', 'Thành công: tăng completedActions, đóng biểu mẫu và nhận dữ liệu Flow mới.'],
         ['Nhập dữ liệu không hợp lệ: giữ nội dung chỉnh sửa, hiện lỗi và không update.', 'Bản ghi đã không còn tồn tại: update trả 0, check thất bại và ViewModel hiển thị actionError.', 'Đổi loại hoặc ngày có thể làm giao dịch không còn phù hợp bộ lọc hiện tại; biến mất khỏi danh sách không đồng nghĩa bị xóa.', 'Hủy: không ghi các chỉnh sửa chưa lưu.'],
         'Chỉ bản ghi đúng ID bị thay đổi. Khoản thu/chi và tổng hợp được tính theo giá trị mới.',
         'Kiểm tra sửa tiền, loại, danh mục, ngày và note; thử tiền âm/0 khi update; kiểm tra ID không đổi.'),
        ('UC05','Xóa giao dịch','Nhấn biểu tượng thùng rác của một dòng','Giao dịch tồn tại; không busy',
         ['Hệ thống ghi deletingId và hiển thị dialog Xóa giao dịch?.', 'Dialog hiển thị tên danh mục, số tiền và thông báo không thể hoàn tác.', 'Người dùng nhấn Xóa để xác nhận.', 'ViewModel bật busy và gọi repository.delete(id).', 'DAO.delete(id) thực thi truy vấn có tham số; repository kiểm tra kết quả đúng 1 dòng.', 'Thành công: đóng dialog, Room phát dữ liệu mới, tổng quan và biểu đồ loại bỏ khoản giao dịch.'],
         ['Hủy hoặc đóng dialog khi không busy: deletingId được xóa khỏi state UI, database không đổi.', 'Không còn bản ghi để xóa hoặc ghi thất bại: hiện actionError, bật lại nút để thử lại.', 'Trong khi busy, không cho xác nhận lặp hay đóng bằng thao tác hủy trong dialog.'],
         'Bản ghi bị xóa bền vững sau khi thành công. Không có chức năng Undo trong bản hiện tại.',
         'Kiểm tra cả xác nhận và hủy; xóa khoản thu/chi; xóa giao dịch cuối cùng; kiểm tra không seed lại sau khi danh sách rỗng.'),
        ('UC06','Chọn khoảng thời gian','Nhấn ‹ / › hoặc nút Theo tháng / Toàn bộ','Dữ liệu đang tải thành công',
         ['Tháng mặc định khi chưa có state là YearMonth.now().', 'Nút ‹ gọi changeMonth(-1); nút › gọi changeMonth(1).', 'Nút Theo tháng/Toàn bộ đảo monthOnly bằng setMonthOnly().', 'SavedStateHandle lưu các giá trị; combine nhận tham số mới.', 'Nếu monthOnly=true, period chỉ có date bắt đầu bằng yyyy-MM- của tháng chọn.', 'Nếu monthOnly=false, period là toàn bộ rows; tháng chọn vẫn làm mốc kết thúc của biểu đồ cột.'],
         ['Tháng không có dữ liệu: tổng thu/chi bằng 0, danh sách rỗng nhưng biểu đồ cột vẫn có 6 tháng.', 'Đổi tháng qua tháng 12/tháng 1 được YearMonth xử lý cả năm.', 'Không giới hạn chọn tháng tương lai; có thể ghi hoặc xem các ngày tương lai trong bản hiện tại.'],
         'Không sửa bất kỳ giao dịch nào. Chỉ thay đổi phạm vi hiển thị và tính toán.',
         'Kiểm tra ranh giới năm, tháng 2 năm nhuận, tháng rỗng và chế độ toàn bộ.'),
        ('UC07','Lọc loại giao dịch','Nhấn chip Tất cả / Thu / Chi ở tab Giao dịch','Đã tải dữ liệu và có period đang chọn',
         ['Tất cả đặt type=ALL; Thu đặt INCOME; Chi đặt EXPENSE.', 'SavedStateHandle phát type mới cho combine.', 'summarize lọc period thành visible theo type.', 'LazyColumn hiển thị visible, số giao dịch thay đổi tương ứng.', 'Thẻ tổng quan, donut và cột vẫn dùng dữ liệu trước bước lọc type.'],
         ['Không có loại giao dịch tương ứng: hiện trạng thái rỗng, không xóa dữ liệu.', 'Bộ lọc còn tác động danh sách gần đây ở Tổng quan khi quay về tab này.', 'Người dùng không có bộ lọc danh mục hoặc ô tìm kiếm trong bản hiện tại.'],
         'Database không đổi. Chỉ danh sách và số lượng visible đổi; income, expense và chart không bị thay đổi bởi type.',
         'So sánh tổng quan trước/sau chọn Thu; kiểm tra cả ALL, INCOME, EXPENSE trong tháng và toàn bộ.'),
        ('UC08','Xem phân bổ chi theo danh mục','Xem donut ở Tổng quan hoặc Thống kê','Dữ liệu đã được tổng hợp',
         ['Lấy các giao dịch EXPENSE trong period.', 'Nhóm theo categoryId bằng groupBy, cộng amount trong mỗi nhóm.', 'Tạo CategoryExpense(id,name,amount), sắp giảm dần theo amount.', 'Vẽ mỗi cung bằng tỷ lệ số tiền danh mục trên tổng expense; màu dựa theo categoryId.', 'Chú giải hiển thị tên và tỷ lệ phần trăm; tab Thống kê hiển thị thêm số tiền chính xác từng nhóm.'],
         ['expense=0: vẽ vòng nền, nhắc thêm khoản chi và tránh chia cho 0.', 'Tỷ lệ chú giải dùng toInt nên làm tròn xuống; tổng phần trăm hiển thị có thể chưa bằng 100.', 'Tên dài được rút gọn trong chú giải; categoryId vẫn xác định nhóm dữ liệu.'],
         'Không ghi dữ liệu; tổng số tiền các nhóm bằng tổng expense trong period.',
         'Kiểm tra nhiều giao dịch cùng danh mục, loại thu không tham gia, tháng không có chi và chọn toàn bộ.'),
        ('UC09','Xem chi tiêu theo tháng','Xem biểu đồ cột ở Tổng quan hoặc Thống kê','Có tháng được chọn làm mốc',
         ['Tạo 6 YearMonth từ month.minusMonths(5) đến month.', 'Với mỗi tháng, lấy các rows có type=EXPENSE và date bắt đầu bằng prefix tháng đó.', 'Cộng amount tạo MonthlyExpense; không có dữ liệu thì nhận 0.', 'Tính giá trị lớn nhất để chuẩn hóa chiều cao cột; nếu tất cả 0 thì max được giữ tối thiểu 1 để tránh chia cho 0.', 'Vẽ cột, nhãn tháng/năm và mô tả truy cập; Thống kê hiển thị thêm giá trị VND từng tháng.'],
         ['Tất cả tháng có chi=0: hiện thông báo Chưa có khoản chi trong giai đoạn này.', 'Bộ lọc type=INCOME không làm các cột về 0.', 'Chọn Toàn bộ không đổi số tháng của biểu đồ; nó vẫn là cửa sổ 6 tháng đến month.'],
         'Database không đổi; cột chỉ thể hiện khoản chi, không thể hiện thu hoặc số dư.',
         'Kiểm tra 6 điểm, ranh giới năm, tháng không có giao dịch và giá trị tiền lớn.')
    ]
    for index,(code,title,trigger,pre,steps,alternatives,post,checks) in enumerate(cases,1):
        r.h(f'3.{index+4}. Đặc tả {code} — {title}')
        r.table(f'Thông tin use case {code}',['Thuộc tính','Đặc tả'],[
            ('Mã / tên',f'{code} — {title}'),('Actor','Người dùng'),('Kích hoạt',trigger),('Tiền điều kiện',pre),('Hậu điều kiện',post)],[3.4,12.6])
        r.h('Luồng chính',3); r.steps(steps)
        r.h('Luồng thay thế và ngoại lệ',3)
        for a in alternatives: r.bullet(a)
        r.h('Điểm kiểm tra khi nghiệm thu',3); r.p(checks)
    r.h('3.14. Ma trận truy vết yêu cầu')
    r.table('Truy vết yêu cầu – use case – mã nguồn – kiểm tra',['Yêu cầu','Use case','Mã chính','Cách kiểm tra'],[
        ('FR01','UC01','ExpenseSummary / DashboardHeader','Unit test + ảnh tổng quan'),('FR02, FR04','UC02, UC04','TransactionEditor / Repository / DAO','Test Room + thao tác UI thêm'),('FR03','UC03','observeTransactions / TransactionTile','Ảnh danh sách và thứ tự truy vấn'),('FR05','UC05','delete / AlertDialog','Test Room + xóa giao dịch thử trên UI'),('FR06, FR07','UC06, UC07','SavedStateHandle / summarize','Unit test period và type'),('FR08','UC08','categoryExpenses / CategoryChart','Unit test groupBy và period'),('FR09','UC09','chart / SpendingChart','Unit test 6 tháng và ranh giới năm'),('FR10','UC02, UC04, UC05','AmountValidator / actionError / loadError','Unit test và ảnh lỗi 0/âm')],[2.3,2.4,6.3,5.0])
